[workspace]
resolver = "3"
members = ["crates/*", "tools/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["joxan2137"]

[workspace.dependencies]
tuck-core = { path = "crates/tuck-core" }
tuck-ui = { path = "crates/tuck-ui" }
tuck-sys = { path = "crates/tuck-sys" }
tuck-clip = { path = "crates/tuck-clip" }
tuck-store = { path = "crates/tuck-store" }
tuck-emoji = { path = "crates/tuck-emoji" }
tuck-panel = { path = "crates/tuck-panel" }

anyhow = "1.0.104"
thiserror = "2.0.21"
log = "0.4.34"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
image = { version = "0.25.10", default-features = false, features = ["png"] }
png = "0.18.1"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
unicode-normalization = "0.1"
unicode-segmentation = "1"
icondata_lu = "0.1.0"
icondata_core = "0.1.0"
embed-resource = "3.0.11"
windows-core = "0.62"
windows-numerics = "0.3.1"
windows-collections = "0.3.2"
windows = { version = "0.62.2", features = [
    "ApplicationModel_DataTransfer",
    "Foundation",
    "Foundation_Collections",
    "Globalization",
    "Graphics",
    "Graphics_DirectX",
    "Graphics_DirectX_Direct3D11",
    "Graphics_Imaging",
    "Media_Ocr",
    "Storage",
    "Storage_Streams",
    "UI_ViewManagement",
    "Win32_Devices_Display",
    "Win32_Foundation",
    "Win32_Globalization",
    "Win32_Graphics_Direct2D",
    "Win32_Graphics_Direct2D_Common",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_DirectComposition",
    "Win32_Graphics_DirectWrite",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Imaging",
    "Win32_Graphics_Imaging_D2D",
    "Win32_Security",
    "Win32_Security_Cryptography",
    "Win32_Storage_FileSystem",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_DataExchange",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
    "Win32_System_Ole",
    "Win32_System_Performance",
    "Win32_System_ProcessStatus",
    "Win32_System_Registry",
    "Win32_System_RemoteDesktop",
    "Win32_System_SystemInformation",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
    "Win32_System_Time",
    "Win32_System_Variant",
    "Win32_System_WinRT",
    "Win32_UI_Accessibility",
    "Win32_UI_Controls",
    "Win32_UI_HiDpi",
    "Win32_UI_Input_Ime",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Input_Pointer",
    "Win32_UI_Shell",
    "Win32_UI_Shell_Common",
    "Win32_UI_Shell_PropertiesSystem",
    "Win32_UI_WindowsAndMessaging",
] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "thin"
codegen-units = 4
panic = "abort"
debug = "line-tables-only"